#include <OpenKNXHardware.h>

#define PROG_LED_PIN_ACTIVE_ON 1
#define PROG_LED_PIN 6
#define PROG_BUTTON_PIN 7

#define KNX_UART_TX_PIN 0
#define KNX_UART_RX_PIN 1

#define DOORBELL_CHANNEL_COUNT 2

#define DOORBELL_DOOR_RINGING_PIN 13
#define DOORBELL_STOREY_RINGING_PIN 15

#define DOORBELL_DEBOUNCE_INTERVAL 50
#define DOORBELL_POLLING_INTERVAL 10

#define ACTIVATE_DOOR_OPENER_PIN 14
#define DOOR_OPENER_DURATION 2500
